### ISSUE TITLE
Setting Flags

### ISSUE THREAD

**Issue by maennchen** [ofek/csi-gcs#19]
I think it would make sense to replace the `flags` parameter with specific config keys.

## Sources Provision

1. `PersistentVolumeClaim` / `annotations`
   - formatted like `gcs.csi.ofek.dev/foo-bar: xyz`
   - forwarded to `PersistentVolume` / `volumeContext` on `CreateVolume`
1. `StorageClass` / `parameters`
   - formatted like `gcs.csi.ofek.dev/foo-bar: xyz`
   - forwarded to `PersistentVolume` / `volumeContext` on `CreateVolume`
1. `StorageClass` / `MountOptions`
   - formatted as string like `--foo-bar="xyz"`
1. `StorageClass` / `csi.storage.k8s.io/provisioner-secret`
   - formatted like `fooBar: xyz`
   - forwarded to `PersistentVolume` / `volumeContext` on `CreateVolume`

## Sources Node

1. `PersistentVolume` / `volumeContext`
   - formatted like `fooBar: xyz`
1. `PersistentVolume` / `MountOptions`
   - formatted as string like `--foo-bar="xyz"`
1. `PersistentVolume` / `nodePublishSecretRef`
   - formatted like `fooBar: xyz`

## Priority

In order of sources.

## Flags

* ~~`foreground`~~ - Not supported since this should be internal to the driver
* `o` - No Validation - Special Note about how this may break stuff, Linking [here](https://manpages.debian.org/testing/fuse/mount.fuse.8.en.html), Internally Renamed to `fuseMountOption`
* `dir-mode` - Validate Number (Octal, permission)
* `file-mode` - Validate Number (Octal, permission)
* `uid` - Validate Number
* `gid` - Validate Number
* `implicit-dirs` - Validate Boolean (`"true"` / `"false"`)
* ~~`only-dir`~~ - Not supported since there is a [K8S way](https://kubernetes.io/docs/concepts/storage/volumes/#using-subpath) for that
* `billing-project` - Validate String
* ~~`key-file`~~ - Not supported since this should be internal to the driver
* `limit-bytes-per-sec` Validate Number
* `limit-ops-per-sec` Validate Number
* `stat-cache-ttl` Validate Number
* `type-cache-ttl` Validate Number
* ~~`temp-dir`~~ - Not supported since this should be internal to the driver
* ~~`debug_*`~~ - Not supported since this should be internal to the driver
* ~~`help`~~ - Not supported since that makes no sense
* ~~`version`~~ - Not supported since that makes no sense

## Docs

* Document all location / flag names
* Add Doc Page / Section for running containers not as root (#6)
  - Always
    * Recommend setting `gid` to any number
    * Recommend setting `Pod/securityContext/fsGroup` to same value
    * Recommend setting `Pod/securityContext/fsGroupChangePolicy` to `OnRootMismatch` to avoid changes since our FS does not support permissions
  - All containers inside pod have same UID
    * Recommend setting `uid` to user id of container
  - Containers inside pod have different UID
    * Set `dir-mode` to `077x` (Allow all users of group)
    * Set `file-mode` to `066x` (Allow all users of group)

## Discussions

* Make setup for usage with non-root users easier?
  - `dir-mode` default `0775` (instead `0755`)
  - `file-mode` default `0664` (instead `0644`)
  - `gid` default `63147` (randomly selected number )
  - This would shorten "Non-Root-Container" Docs to only do the steps `Pod/securityContext/fsGroup` and `Pod/securityContext/fsGroupChangePolicy`

**Comment by maennchen** [comment]
To make cases like #6 clearer.

**Comment by ofek** [comment]
This makes a lot of sense, great idea!

**Comment by maennchen** [comment]
Examples:

`StorageClass` with `mountOptions`

```yml
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: csi-gcs
provisioner: gcs.csi.ofek.dev
volumeBindingMode: Immediate
allowVolumeExpansion: false
reclaimPolicy: Delete
parameters:
  csi.storage.k8s.io/node-publish-secret-name: csi-gcs-secret-mounter
  csi.storage.k8s.io/node-publish-secret-namespace: default
  csi.storage.k8s.io/provisioner-secret-name: csi-gcs-secret-creator
  csi.storage.k8s.io/provisioner-secret-namespace: default
mountOptions:
  - '--gid=400'
```

`PersistentVolumeClaim` with `Annotations`

```yml
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: csi-gcs-pvc
  annotations:
    gcs.csi.ofek.dev/location: asia
    gcs.csi.ofek.dev/project-id: joshmartin-csi-gcs-test
    gcs.csi.ofek.dev/fuse-mount-option: 'uid=7,gid=8'
spec:
  storageClassName: csi-gcs
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
```

**Comment by maennchen** [comment]
`PersistentVolume` with `mountOptions`

```yml
apiVersion: v1
kind: PersistentVolume
metadata:
  name: csi-gcs-pv
spec:
  accessModes:
  - ReadWriteOnce
  capacity:
    storage: 5Gi
  persistentVolumeReclaimPolicy: Retain
  storageClassName: csi-gcs-test-sc
  mountOptions:
    - '--gid=400'
  csi:
    driver: gcs.csi.ofek.dev
    volumeHandle: csi-gcs
    nodePublishSecretRef:
      name: csi-gcs-secret
      namespace: default
```
