### ISSUE TITLE
StorageClass definition (static example)

### ISSUE THREAD

**Issue by mweibel** [ofek/csi-gcs#77]
Hi,

I was looking into the examples and wondered where the storage class definition is for the static example. It references `csi-gcs-test-sc` but I couldn't find that.

I guess it sorta works also without it, but not sure.
Any pointers?

Cheers,
Michael

**Comment by maennchen** [comment]
@mweibel I don't think we ever had a static example with a StorageClass since it works without it as well if you provision manually.

You should be able to reuse parts of the dynamic example: https://github.com/ofek/csi-gcs/blob/master/examples/dynamic/sc.yaml

I think this should be sufficient:

```yml
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: csi-gcs-test-sc
provisioner: gcs.csi.ofek.dev
```

Can you try that?

If it works, a quick PR adding this file to the example dir would be very welcome :)
